/**
 * ESC/POS command builders for the counter's Epson TM-T82X (80mm thermal).
 *
 * This replaces the LX-310's ESC/P renderer. The difference is not just the
 * command set: the old form was PRE-PRINTED and we overprinted values into its
 * boxes, so every value needed an absolute row/column and every counter needed
 * calibrating. Here we print the whole ticket onto blank roll, so the document
 * is a top-to-bottom flow of lines and there is nothing to align.
 *
 * TM-T82X geometry: 203 dpi, 72mm printable = 576 dots.
 *   • Font A is 12x24 dots -> 48 characters per line
 *   • Font B is 9x17 dots  -> 64 characters per line
 *
 * The QR is generated BY THE PRINTER from the token (GS ( k), not rasterised
 * here — no bitmap crosses the wire, and there is no dpi or scaling to get
 * wrong. The payload is the bare `qr_token` UUID, which is exactly what the
 * boarding gate posts to the verification server.
 *
 * Bytes go to the counter's print agent, which hands them to the Windows
 * spooler with the RAW datatype so nothing rewrites them on the way out.
 */

const ESC = 0x1b;
const GS = 0x1d;
const LF = 0x0a;

/** Characters per line, by font. */
export const FONT_A_COLS = 48;
export const FONT_B_COLS = 64;

export type Align = "left" | "center" | "right";
export type Font = "A" | "B";

/** QR error correction. M (~15%) is plenty for a 36-char token on fresh
 *  thermal; H is available if tickets come back scuffed. */
export type QrEc = "L" | "M" | "Q" | "H";

// ── Character sanitising ────────────────────────────────────────────────────
// The printer runs an 8-bit code page (PC437 by default), not UTF-8. Anything
// outside printable ASCII would come out as garbage glyphs, so fold it first.
// The peso sign in particular has to become "P" — which is also how the
// operator's existing tickets read.
const TRANSLITERATE: Record<string, string> = {
  "₱": "P",
  "–": "-",
  "—": "-",
  "‘": "'",
  "’": "'",
  "“": '"',
  "”": '"',
  "…": "...",
  "°": " ",
};

export function toPrintable(input: string): string {
  let s = input ?? "";
  for (const [from, to] of Object.entries(TRANSLITERATE)) s = s.split(from).join(to);
  // Strip accents (é → e) before the final ASCII filter so names stay readable.
  s = s.normalize("NFD").replace(/[̀-ͯ]/g, "");
  let out = "";
  for (const ch of s) {
    const c = ch.codePointAt(0)!;
    if (c === 9) out += " ";
    else if (c >= 32 && c <= 126) out += ch;
    else if (c > 126) out += "?";
    // Other control characters are dropped — they would be read as commands.
  }
  return out;
}

// ── Byte writer ─────────────────────────────────────────────────────────────

export class EscposWriter {
  private bytes: number[] = [];

  raw(...b: number[]) {
    this.bytes.push(...b);
    return this;
  }

  /** ASCII only — text is folded through `toPrintable` first. */
  text(s: string) {
    const clean = toPrintable(s);
    for (let i = 0; i < clean.length; i++) this.bytes.push(clean.charCodeAt(i) & 0xff);
    return this;
  }

  /** ESC @ — reset, so a job left over from another app cannot bleed settings in. */
  init() {
    return this.raw(ESC, 0x40);
  }

  /** ESC a n — 0 left, 1 centre, 2 right. */
  align(a: Align) {
    return this.raw(ESC, 0x61, a === "center" ? 1 : a === "right" ? 2 : 0);
  }

  /** ESC M n — 0 Font A (48 cols), 1 Font B (64 cols). */
  font(f: Font) {
    return this.raw(ESC, 0x4d, f === "B" ? 1 : 0);
  }

  /** GS ! n — width/height multipliers, 1-8 each, packed into one byte. */
  size(width = 1, height = 1) {
    const w = Math.max(1, Math.min(8, width)) - 1;
    const h = Math.max(1, Math.min(8, height)) - 1;
    return this.raw(GS, 0x21, (w << 4) | h);
  }

  /** ESC E n — emphasised. */
  bold(on: boolean) {
    return this.raw(ESC, 0x45, on ? 1 : 0);
  }

  /** ESC - n — underline off/1-dot/2-dot. */
  underline(dots: 0 | 1 | 2) {
    return this.raw(ESC, 0x2d, dots);
  }

  line(s = "") {
    return this.text(s).raw(LF);
  }

  /** ESC d n — feed n lines. */
  feed(lines = 1) {
    return this.raw(ESC, 0x64, Math.max(0, Math.min(255, lines)));
  }

  /**
   * GS ( L — print a graphic already stored in the printer's NV flash.
   *
   * The Aleson logo is uploaded once per printer with Epson's TM utility under a
   * two-character key code; nothing about it travels with the job. If the key is
   * absent the printer simply prints nothing, so a printer that never had the
   * logo loaded still produces a usable ticket.
   */
  nvGraphic(kc1: string, kc2: string, scaleX = 1, scaleY = 1) {
    return this.raw(
      GS, 0x28, 0x4c, 0x06, 0x00, 0x30, 0x45,
      kc1.charCodeAt(0), kc2.charCodeAt(0), scaleX, scaleY
    );
  }

  /**
   * GS ( k — have the printer generate and print a QR from `data`.
   *
   * Four commands in sequence: select model, set module size, set error
   * correction, store the data, then print what was stored.
   */
  qr(data: string, moduleSize = 6, ec: QrEc = "M") {
    const payload = toPrintable(data);
    // Select model 2.
    this.raw(GS, 0x28, 0x6b, 0x04, 0x00, 0x31, 0x41, 0x32, 0x00);
    // Module size in dots (1-16). At 203 dpi, 6 gives roughly a 25mm code.
    this.raw(GS, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x43, Math.max(1, Math.min(16, moduleSize)));
    // Error correction: 48=L, 49=M, 50=Q, 51=H.
    const ecByte = { L: 48, M: 49, Q: 50, H: 51 }[ec];
    this.raw(GS, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x45, ecByte);
    // Store the payload. pL/pH count the data plus the three header bytes.
    const len = payload.length + 3;
    this.raw(GS, 0x28, 0x6b, len & 0xff, (len >> 8) & 0xff, 0x31, 0x50, 0x30);
    this.text(payload);
    // Print what was stored.
    return this.raw(GS, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x51, 0x30);
  }

  /** GS V 66 n — partial cut after feeding n dots clear of the blade. */
  cut(feedDots = 0x50) {
    return this.raw(GS, 0x56, 0x42, Math.max(0, Math.min(255, feedDots)));
  }

  toUint8Array() {
    return Uint8Array.from(this.bytes);
  }
}

// ── Line helpers ────────────────────────────────────────────────────────────

/** A full-width rule, e.g. "--------". */
export const rule = (cols: number, ch = "-") => ch.repeat(Math.max(0, cols));

/**
 * "LABEL................VALUE" across the line width. The value is never
 * truncated in favour of the label — a fare or a ticket number matters more
 * than its caption, so an over-long pair drops the filler and wraps naturally.
 */
export function pair(label: string, value: string, cols: number, filler = " "): string {
  const l = toPrintable(label);
  const v = toPrintable(value);
  const gap = cols - l.length - v.length;
  return gap > 0 ? l + filler.repeat(gap) + v : `${l} ${v}`;
}

/** Break text onto `cols`-wide lines at word boundaries. */
export function wrap(text: string, cols: number): string[] {
  const words = toPrintable(text).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if (!cur.length) cur = w;
    else if (cur.length + 1 + w.length <= cols) cur += ` ${w}`;
    else {
      lines.push(cur);
      cur = w;
    }
  }
  if (cur.length) lines.push(cur);
  return lines;
}

// ── Base64 ──────────────────────────────────────────────────────────────────
// Hand-rolled because `btoa` is web-only and `Buffer` is native-only, and this
// module has to work in both halves of the Expo build.

const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

export function bytesToBase64(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i];
    const b1 = bytes[i + 1];
    const b2 = bytes[i + 2];
    out += B64[b0 >> 2];
    out += B64[((b0 & 3) << 4) | ((b1 ?? 0) >> 4)];
    out += b1 === undefined ? "=" : B64[((b1 & 15) << 2) | ((b2 ?? 0) >> 6)];
    out += b2 === undefined ? "=" : B64[b2 & 63];
  }
  return out;
}

/** Concatenate several rendered tickets into one spooler job. */
export function concatBytes(chunks: Uint8Array[]): Uint8Array {
  const total = chunks.reduce((n, c) => n + c.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const c of chunks) {
    out.set(c, at);
    at += c.length;
  }
  return out;
}
